# Generated by Django 4.2.1 on 2023-06-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='file_upload',
            fields=[
                ('ids', models.AutoField(primary_key=True, serialize=False)),
                ('my_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('ids', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('path', models.FilePathField(default='/home/madbrush/Documents/edisk/media/', path='/home/madbrush/Documents/edisk/media/')),
            ],
        ),
    ]
