# Generated by Django 4.2.1 on 2023-06-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='storage_space',
            field=models.FloatField(default=0.0),
        ),
    ]
