# Generated by Django 4.2.1 on 2023-06-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='upload_dir',
            field=models.CharField(default='upload_dir', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='storage_space',
            field=models.IntegerField(default=1073741824),
        ),
    ]
