# Generated by Django 4.2.1 on 2023-06-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_upload_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='used_storage_space',
            field=models.IntegerField(default=0),
        ),
    ]
