# Generated by Django 4.2.1 on 2023-06-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_upload_dir_alter_user_storage_space'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='upload_dir',
        ),
        migrations.AddField(
            model_name='user',
            name='upload_path',
            field=models.CharField(default='/home/madbrush/Documents/edisk/media/', max_length=255),
        ),
    ]
